---
title: "In_class_EX03"
author: "HuYu"
---

```{r}
pacman::p_load(sf, spNetwork, tmap, tidyverse)
```

```{r}
network <- st_read(dsn="/Users/yuhu/Desktop/Geospatial Analytics and Applications/Hands-on EX03/geospatial", 
                   layer="Punggol_St")
```

```{r}
childcare <- st_read(dsn="/Users/yuhu/Desktop/Geospatial Analytics and Applications/Hands-on EX03/geospatial",
                     layer="Punggol_CC")
```

```{r}
childcare
```

```{r}
network
```

```{r}
plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
plot(network)
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
tmap_mode('view')
```

```{r}
tmap_mode('view')
tm_shape(childcare) + 
  tm_dots() + 
  tm_shape(network) +
  tm_lines()
```

```{r}
tmap_mode('plot')
```

```{r}
lixels <- lixelize_lines(network, 
                         700, 
                         mindist = 375)
```

```{r}
samples <- lines_center(lixels) 
```

```{r}

tmap_mode('view')
```

```{r}
tm_shape(lixels) +
  tm_lines() +
tm_shape(samples) +
  tm_dots(size = 0.01)
```

```{r}
tmap_mode('plot')
```

```{r}
densities <- nkde(network, 
                  events = childcare,
                  w = rep(1, nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple")
```

```{r}
kfun_childcare <- kfunctions(network, 
                             childcare,
                             start = 0, 
                             end = 1000, 
                             step = 50, 
                             width = 50, 
                             nsim = 50, 
                             resolution = 50,
                             verbose = FALSE, 
                             conf_int = 0.05)
```

```{r}
kfun_childcare$plotk
```
