---
title: "In_class_Ex02"
author: "HuYu"
---

```{r}
install.packages("maptools",
                repos = "https://packagemanager.posit.co/cran/2023-10-13")
```

```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse)
```

```{r}
mpsz_sf <- st_read(dsn = "/Users/yuhu/ISSS626/Hands_on_EX/Hands_on_EX10/data/geospatial", 
                layer = "MP14_SUBZONE_WEB_PL") %>%
  st_transform(crs = 3414)
```

```{r}
sg_sf <- mpsz_sf %>%
  st_union
plot(sg_sf)
```

```{r}
childcare_sf <- st_read("/Users/yuhu/Desktop/Geospatial Analytics and Applications/Hands-on Ex02/data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
childcare_ppp <- as.ppp(childcare_sf)
```

```{r}
sg_owin <- as.owin(sg_sf)
```

```{r}
childcareSG_ppp = childcare_ppp[sg_owin]
```

```{r}
kde_childcareSG_bw <- density(childcareSG_ppp,
                              sigma=bw.diggle,
                              edge=TRUE,
                            kernel="gaussian") 
```

```{r}
childcareSG_ppp.km <- rescale.ppp(childcareSG_ppp, 1000, "km")

kde_childcareSG_adaptive <- adaptive.density(childcareSG_ppp.km, method="kernel")

gridded_kde_childcareSG_ad <- as(
  kde_childcareSG_adaptive,
  "SpatialGridDataFrame"
)
spplot(gridded_kde_childcareSG_ad)
```

```         
```
