---
title: "In-class Exercise01"
author: "HuYu"
date: "Aug 20 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

```{r}
pacman::p_load(sf, tidyverse, tmap, ggstatsplot)
```

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(ggstatsplot)
```

```{r}
mpsz14_shp = st_read(dsn = "/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/Data/geospatial", 
                  layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
st_write(
  mpsz14_shp, 
  "/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/Data/geospatial/MP14_SUBZONE_WEB_PL.kml",
  delete_dsn = TRUE
)
```

```{r}
preschool_kml <- st_read("/Users/yuhu/Desktop/Geospatial Analytics and Applications/Hands-on Ex01/Data/PreSchoolsLocation.kml")
```

```{r}
preschool_geojson <- st_read("/Users/yuhu/Desktop/Geospatial Analytics and Applications/Hands-on Ex01/Data/PreSchoolsLocation.geojson") 
```

```{r}
mpsz19_shp = st_read(dsn = "/Users/yuhu/Desktop/Geospatial Analytics and Applications/MPSZ-2019/", 
                  layer = "MPSZ-2019")
mpsz19_shp <- st_transform(mpsz19_shp, crs = 3414)
```

```{r}
st_write(mpsz14_shp, 
         "/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/data/geospatial/MP14_SUBZONE_WEB_PL.kml",
         delete_dsn = TRUE)
```

```{r}
mpsz19_kml <- st_read("/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaKML.kml")
```

```{r}
st_crs(mpsz19_shp)
```

```{r}
preschool <- st_read("/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/data/geospatial/PreSchoolsLocation.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
mpsz19_shp <- st_read(dsn = "/Users/yuhu/Desktop/Geospatial Analytics and Applications/In-class- EX01/MPSZ-2019",
                layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
```

```{r}
mpsz19_shp <- mpsz19_shp %>%
  mutate(`PreSch Count` = lengths(
    st_intersects(mpsz19_shp, preschool)))
```

```{r}
mpsz19_shp <- mpsz19_shp %>%
  mutate(Area = units::drop_units(
    st_area(.)),
    `PreSch Density` = `PreSch Count` / Area * 1000000
  )
```

```{r}
mpsz19_shp <- mpsz19_shp[1:323, ]
```

```{r}
mpsz$`PreSch Density` <- as.numeric(as.character(mpsz19_shp$`PreSch Density`))
mpsz$`PreSch Count` <- as.numeric(as.character(mpsz19_shp$`PreSch Count`)) 
mpsz19_shp <- as.data.frame(mpsz19_shp)

ggscatterstats(data = mpsz19_shp,
               x = `PreSch Density`,
               y = `PreSch Count`,
               type = "parametric")
```

```{r}
popdata <- read_csv("/Users/yuhu/Desktop/Data Analytics Lab/Session 3/respopagesextod2022/respopagesextod2022.csv")
```

```{r}
popdata2022 <- popdata %>% 
  group_by(PA, SZ, AG) %>% 
  summarise(`POP`=sum(`Pop`)) %>%  
  ungroup() %>% 
  pivot_wider(names_from=AG,
              values_from = POP)

colnames(popdata2022)
```

```{r}
popdata2023 <- popdata2022 %>%
  mutate(YOUNG=rowSums(.[3:6]) # Aged 0 - 24, 10 - 24
         +rowSums(.[14])) %>% # Aged 5 - 9
  mutate(`ECONOMY ACTIVE` = rowSums(.[7:13])+ # Aged 25 - 59
  rowSums(.[15])) %>%  # Aged 60 -64
  mutate(`AGED`=rowSums(.[16:21])) %>%
  mutate(`TOTAL`=rowSums(.[3:21])) %>%
  mutate(`DEPENDENCY`=(`YOUNG` + `AGED`)
  / `ECONOMY ACTIVE`) %>% 
  select(`PA`, `SZ`, `YOUNG`, 
         `ECONOMY ACTIVE`, `AGED`,
         `TOTAL`, `DEPENDENCY`)
```

```{r}
popdata2023 <- popdata2023 %>%
  mutate_at(.vars = vars(PA, SZ), 
          .funs = list(toupper)) 
```

```{r}
mpsz_pop2023 <- left_join(mpsz19_shp, popdata2023,
                          by = c("SUBZONE_N" = "SZ"))
```

```{r}
pop2023_mpsz <- left_join(popdata2023, mpsz19_shp, 
                          by = c("SZ" = "SUBZONE_N"))
```

```{r}
write_rds(mpsz_pop2023, "/Users/yuhu/Desktop/ISSS626_GAA/_site/In-class_Ex/In-class_EX01/data/geospatial/mpszpop2023.rds")
```

```{r}
mpsz_pop2023 <- st_as_sf(mpsz_pop2023)
```

```{r}
tm_shape(mpsz_pop2023) +
  tm_polygons()
```

```{r}
qtm(mpsz_pop2023, 
    fill = "DEPENDENCY")
```
